@props([
    'view' => null,
    'defaultView' => null,
    'date' => null,
    'defaultDate' => null,
    'events' => [],
    'availability' => [],
    'startHour' => 7,
    'endHour' => 21,
    'weekStartsOn' => 1,
    'slotStep' => 30,
    'locale' => 'en-US',
    'labels' => [],
])

{{--
    CalendarView follows the served Alpine markup in lyra-ds/lyra. Calendar cells and chips
    are generated by Intl and local-time geometry after Alpine starts. The root owns x-data;
    put application state on a parent and use x-model for date (or view via x-modelable).
    Pass the popover and toolbar-actions named slots for the React render prop equivalents.
--}}
@php
    $requestedModelable = $attributes->get('x-modelable');
    $attributes = \LyraDs\Blade\OwnedRoot::guard($attributes, 'calendar-view', ['x-modelable']);
    $modelable = in_array($requestedModelable, ['date', 'view'], true) ? $requestedModelable : 'date';
    $options = [];
    $initialView = $view ?? $defaultView;
    $initialDate = $date ?? $defaultDate;
    if ($initialView !== null) $options['defaultView'] = $initialView;
    if ($initialDate !== null) $options['defaultDate'] = $initialDate;
    if ($events !== []) $options['events'] = $events;
    if ($availability !== []) $options['availability'] = $availability;
    if ((int) $startHour !== 7) $options['startHour'] = (int) $startHour;
    if ((int) $endHour !== 21) $options['endHour'] = (int) $endHour;
    if ((int) $weekStartsOn !== 1) $options['weekStartsOn'] = (int) $weekStartsOn;
    if ((int) $slotStep !== 30) $options['slotStep'] = (int) $slotStep;
    if ($locale !== 'en-US') $options['locale'] = $locale;
    if ($labels !== []) $options['labels'] = $labels;
    $optionsLiteral = json_encode(
        $options === [] ? (object) [] : $options,
        JSON_THROW_ON_ERROR | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT
            | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE,
    );
    $resolvedLabels = array_merge([
        'previous' => 'Previous period',
        'today' => 'Today',
        'next' => 'Next period',
        'view' => 'Calendar view',
        'day' => 'Day',
        'week' => 'Week',
        'month' => 'Month',
        'hours' => 'Calendar hours',
    ], is_array($labels) ? $labels : []);
    $rootAttributes = $attributes->except(['x-modelable'])->class('lyra-calview');
@endphp

<div x-data="{{ 'lyraCalendarView('.$optionsLiteral.')' }}" x-modelable="{{ $modelable }}" {{ $rootAttributes }}>
    <div class="lyra-calview__toolbar">
        <button class="lyra-calview__nav" type="button" aria-label="{{ $resolvedLabels['previous'] }}" :aria-label="label('previous')" x-on:click="navigate(-1)"><x-lyra::icon name="chevron-left" :size="16" /></button>
        <button class="lyra-calview__nav" type="button" aria-label="{{ $resolvedLabels['today'] }}" :aria-label="label('today')" title="{{ $resolvedLabels['today'] }}" :title="label('today')" x-on:click="setDate(new Date())"><x-lyra::icon name="circle-dot" :size="14" /></button>
        <button class="lyra-calview__nav" type="button" aria-label="{{ $resolvedLabels['next'] }}" :aria-label="label('next')" x-on:click="navigate(1)"><x-lyra::icon name="chevron-right" :size="16" /></button>
        <span class="lyra-calview__title" x-text="title()"></span>
        <span class="lyra-calview__seg" role="group" aria-label="{{ $resolvedLabels['view'] }}" :aria-label="label('view')">
            <button type="button" :aria-pressed="view === 'day'" x-on:click="setView('day')" x-text="label('day')">{{ $resolvedLabels['day'] }}</button>
            <button type="button" :aria-pressed="view === 'week'" x-on:click="setView('week')" x-text="label('week')">{{ $resolvedLabels['week'] }}</button>
            <button type="button" :aria-pressed="view === 'month'" x-on:click="setView('month')" x-text="label('month')">{{ $resolvedLabels['month'] }}</button>
        </span>
        @isset($toolbarActions){{ $toolbarActions }}@endisset
    </div>

    <div x-show="view !== 'month'">
        <div class="lyra-calview__head" :style="gridStyle()">
            <span></span>
            <template x-for="day in days()" :key="day.key">
                <span class="lyra-calview__head-cell" :class="dayClass(day)">
                    <span x-text="weekdayLabel(day)"></span><strong x-text="day.date.getDate()"></strong>
                </span>
            </template>
        </div>
        <div class="lyra-calview__scroll" tabindex="0" aria-label="{{ $resolvedLabels['hours'] }}">
            <div class="lyra-calview__grid" :style="gridStyle()">
                <div class="lyra-calview__ruler" :style="{ height: gridHeight() + 'px' }">
                    <template x-for="hour in hours()" :key="hour">
                        <span class="lyra-calview__hour" :style="hourStyle(hour)" x-text="String(hour).padStart(2, '0') + ':00'"></span>
                    </template>
                </div>
                <template x-for="day in days()" :key="day.key">
                    <div class="lyra-calview__col" :style="{ height: gridHeight() + 'px', backgroundSize: '100% 48px' }" x-on:click="createSlot($event, day)">
                        <template x-for="(window, index) in day.windows" :key="index">
                            <span class="lyra-calview__avail" :style="availabilityStyle(window)"></span>
                        </template>
                        <span class="lyra-calview__now" x-show="nowStyle(day)" :style="nowStyle(day) || {}"></span>
                        <template x-for="item in day.events" :key="item.id">
                            <button class="lyra-calview__evt" :class="{ ['lyra-calview__evt--' + item.kind]: true }" :style="eventStyle(item)" type="button" :aria-label="eventLabel(item)" x-on:click="openEvent($event, item)">
                                <span class="lyra-calview__evt-time" x-text="time(item.startDate) + '–' + time(item.endDate)"></span>
                                <span class="lyra-calview__evt-title" x-show="parseFloat(eventStyle(item).height) >= 34" x-text="item.title"></span>
                            </button>
                        </template>
                    </div>
                </template>
            </div>
            @isset($popover)
                <div class="lyra-calview__pop" role="dialog" :aria-label="popover?.event.title" x-show="popover" x-cloak :style="popover ? { top: popover.top + 'px', left: popover.left + 'px' } : {}">
                    {{ $popover }}
                </div>
            @endisset
        </div>
    </div>
    <div class="lyra-calview__mgrid" x-show="view === 'month'" x-cloak>
        <template x-for="(name, index) in weekdays()" :key="index">
            <span class="lyra-calview__head-cell" x-text="name"></span>
        </template>
        <template x-for="day in days()" :key="day.key">
            <button class="lyra-calview__mcell" type="button" :class="monthClass(day)" x-on:click="selectMonthDay(day)">
                <span class="lyra-calview__mday" x-text="day.date.getDate()"></span>
                <template x-for="item in monthEvents(day)" :key="item.id">
                    <span class="lyra-calview__mevt" :class="{ ['lyra-calview__evt--' + item.kind]: true }" x-text="time(item.startDate) + ' ' + item.title"></span>
                </template>
                <span class="lyra-calview__more" x-show="monthMore(day)" x-text="'+' + monthMore(day)"></span>
            </button>
        </template>
    </div>
</div>
